version: '3.0'

services:
  conveyor-node:
    image: samtecspg/conveyor-node:repo-head
    environment:
     - KIBANA_VERSION=${ELASTIC_TAG:-7.6.2}
    ports:
      - '0.0.0.0:4000:4000'
      - '0.0.0.0:1880:1880'
    networks:
      conveyor-net:
        aliases:
          - api
          - node-red
    volumes:
      - ${NODERED_CONFIG:-./local-storage/node-red}:/usr/src/data
    depends_on:
      - elasticsearch
    command: ["dockerize", "-wait", "tcp://elasticsearch:9200", "-timeout", "5m", "node", "start.js"]
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_TAG:-7.6.2}
    environment:
     - ES_JAVA_OPTS=${ES_RAM:--Xmx4g -Xms4g}
    ports: ['9200:9200']
    networks: ['conveyor-net']
    volumes:
      - ${ES_CONFIG:-./local-storage/elasticsearch/config/elasticsearch.yml}:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${ES_DATA:-./local-storage/elasticsearch/data}:/usr/share/elasticsearch/data
    healthcheck:
      test: ['CMD', 'curl', '-f', '-u', '${ES_USER:-elastic}:${ES_PASSWORD:-changeme}', 'http://localhost:9200']
      interval: 1m30s
      timeout: 10s
      retries: 3
  conveyorized-kibana:
    image: bytes/conveyorized-kibana:repo-head
    ports: ['5601:5601']
    networks:
      conveyor-net:
        aliases:
          - kibana
    volumes:
      - ${KIBANA_CONFIG:-./local-storage/kibana/config/kibana.yml}:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
      - conveyor-node
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5601/login']
      interval: 1m30s
      timeout: 10s
      retries: 3
  channel-load:
    image: samtecspg/conveyor-channel-init:repo-head
    networks: ['conveyor-net']
    depends_on:
      - elasticsearch
      - conveyor-node
      - conveyorized-kibana
networks:
  conveyor-net:
